In [52]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

from sklearn import preprocessing


In [53]:
data_train = pd.read_csv("Train/Train_Data.csv")


In [54]:
empty = np.where(pd.isnull(data_train))
print(empty[0].shape)
coloumns_name = data_train.columns
print(coloumns_name[0])

(5265,)
Id


In [55]:
for i in range(empty[0].shape[0]):
    for j in range(empty[1].shape[0]):
        row_no = empty[0][i]
        col_no = empty[1][j]
        col = coloumns_name[col_no]
        data_train.at[row_no,col] = -1
        


In [56]:
empty2 = np.where(pd.isnull(data_train))
print(empty2)

(array([], dtype=int64), array([], dtype=int64))


In [57]:
for col_name in data_train.columns:
    le= preprocessing.LabelEncoder()
    print(col_name)
    data_train[col_name] = le.fit_transform(data_train[col_name])
    print(1)

Id
1
MSSubClass
1
MSZoning
1
LotFrontage
1
LotArea
1
Street
1
Alley
1
LotShape
1
LandContour
1
Utilities
1
LotConfig
1
LandSlope
1
Neighborhood
1
Condition1
1
Condition2
1
BldgType
1
HouseStyle
1
OverallQual
1
OverallCond
1
YearBuilt
1
YearRemodAdd
1
RoofStyle
1
RoofMatl
1
Exterior1st
1
Exterior2nd
1
MasVnrType
1
MasVnrArea
1
ExterQual
1
ExterCond
1
Foundation
1
BsmtQual
1
BsmtCond
1
BsmtExposure
1
BsmtFinType1
1
BsmtFinSF1
1
BsmtFinType2
1
BsmtFinSF2
1
BsmtUnfSF
1
TotalBsmtSF
1
Heating
1
HeatingQC
1
CentralAir
1
Electrical
1
1stFlrSF
1
2ndFlrSF
1
LowQualFinSF
1
GrLivArea
1
BsmtFullBath
1
BsmtHalfBath
1
FullBath
1
HalfBath
1
BedroomAbvGr
1
KitchenAbvGr
1
KitchenQual
1
TotRmsAbvGrd
1
Functional
1
Fireplaces
1
FireplaceQu
1
GarageType
1
GarageYrBlt
1
GarageFinish
1
GarageCars
1
GarageArea
1
GarageQual
1
GarageCond
1
PavedDrive
1
WoodDeckSF
1
OpenPorchSF
1
EnclosedPorch
1
3SsnPorch
1
ScreenPorch
1
PoolArea
1
PoolQC
1
Fence
1
MiscFeature
1
MiscVal
1
MoSold
1
YrSold
1
SaleType
1
SaleConditi

In [58]:
data_train

Id  MSSubClass  MSZoning  LotFrontage  LotArea  Street  Alley  \
0        0           5         3            0      269       1      0   
1        1           0         3            0      403       1      0   
2        2           5         3            0      556       1      0   
3        3           6         3            0      397       1      0   
4        4           5         3            0      738       1      0   
...    ...         ...       ...          ...      ...     ...    ...   
1095  1095           0         3            0      372       1      0   
1096  1096           6         4            0      139       1      0   
1097  1097          11         3            0       45       1      0   
1098  1098           4         4            0      109       1      0   
1099  1099           0         3            0      606       1      0   

      LotShape  LandContour  Utilities  ...  PoolArea  PoolQC  Fence  \
0            3            3          0  ...         0       0      0   
1            3            3          0  ...         0       0      0   
2            0            3          0  ...         0       0      0   
3            0            3          0  ...         0       0      0   
4            0            3          0  ...         0       0      0   
...        ...          ...        ...  ...       ...     ...    ...   
1095         0            3          0  ...         0       0      0   
1096         3            3          0  ...         0       0      0   
1097         3            3          0  ...         0       0      0   
1098         3            3          0  ...         0       0      0   
1099         0            3          0  ...         0       0      0   

      MiscFeature  MiscVal  MoSold  YrSold  SaleType  SaleCondition  SalePrice  
0               0        0       1       2         8              4        360  
1               0        0       4       1         8              4        297  
2               0        0       8       2         8              4        385  
3               0        0       1       0         8              0        170  
4               0        0      11       2         8              4        429  
...           ...      ...     ...     ...       ...            ...        ...  
1095            0        0       2       1         8              4        277  
1096            0        0       2       1         8              4        124  
1097            0        0       9       1         8              4        260  
1098            0        0       6       3         8              4        126  
1099            0        0       3       3         0              0        219  

[1100 rows x 81 columns]

In [59]:
data_train.shape
data_train = data_train.values

In [60]:
Xt = data_train[:,1:-1]
Yt = data_train[:,-1]


In [61]:
print(Xt.shape)
print(Yt.shape)

(1100, 79)
(1100,)


In [62]:
x_train = Xt[:700]
x_val = Xt[700:]
y_train = Yt[:700]
y_val = Yt[700:]


In [63]:
print(x_train.shape,y_train.shape)
print(x_val.shape,y_val.shape)

(700, 79) (700,)
(400, 79) (400,)


In [64]:
Dense?

In [73]:
from keras import models
from keras.layers import Dense

In [94]:
model = models.Sequential()
model.add(Dense(20,activation='relu'))
model.add(Dense(20,activation = 'relu'))
model.add(Dense(1))

In [95]:
model.compile(optimizer='Adam',loss = 'mean_squared_error',metrics=['mae'])

In [96]:
hist = model.fit(x_train,y_train,epochs = 150,batch_size=100,validation_data=(x_val,y_val))

Train on 700 samples, validate on 400 samples
Epoch 1/150
700/700 [==============================] - 0s 363us/step - loss: 28835.3956 - mae: 133.6874 - val_loss: 18927.2290 - val_mae: 108.9975
Epoch 2/150
700/700 [==============================] - 0s 16us/step - loss: 17138.4040 - mae: 102.8042 - val_loss: 12518.9854 - val_mae: 90.3184
Epoch 3/150
700/700 [==============================] - 0s 17us/step - loss: 12651.9907 - mae: 89.5623 - val_loss: 11302.3403 - val_mae: 86.1238
Epoch 4/150
700/700 [==============================] - 0s 19us/step - loss: 11598.9911 - mae: 86.0426 - val_loss: 10633.5979 - val_mae: 83.0866
Epoch 5/150
700/700 [==============================] - 0s 19us/step - loss: 10481.1087 - mae: 81.3816 - val_loss: 9386.5032 - val_mae: 77.8180
Epoch 6/150
700/700 [==============================] - 0s 20us/step - loss: 9271.4348 - mae: 76.6850 - val_loss: 8466.4603 - val_mae: 74.0987
Epoch 7/150
700/700 [==============================] - 0s 20us/step - loss: 8562.8682 - m

Epoch 114/150
700/700 [==============================] - 0s 20us/step - loss: 2208.2147 - mae: 33.8763 - val_loss: 2773.2273 - val_mae: 38.6690
Epoch 115/150
700/700 [==============================] - 0s 20us/step - loss: 2190.0002 - mae: 33.9159 - val_loss: 2769.0308 - val_mae: 38.5663
Epoch 116/150
700/700 [==============================] - 0s 20us/step - loss: 2186.2277 - mae: 33.6283 - val_loss: 2764.4911 - val_mae: 38.5990
Epoch 117/150
700/700 [==============================] - 0s 19us/step - loss: 2173.8952 - mae: 33.3691 - val_loss: 2769.4406 - val_mae: 38.7291
Epoch 118/150
700/700 [==============================] - 0s 17us/step - loss: 2189.9213 - mae: 34.1894 - val_loss: 2795.1880 - val_mae: 38.7527
Epoch 119/150
700/700 [==============================] - 0s 17us/step - loss: 2187.5548 - mae: 33.3664 - val_loss: 2765.6166 - val_mae: 38.7579
Epoch 120/150
700/700 [==============================] - 0s 17us/step - loss: 2156.0381 - mae: 33.7828 - val_loss: 2786.2748 - val_mae: 

In [97]:
model.evaluate(x_train,y_train)

700/700 [==============================] - 0s 14us/step


[1992.5366385323662, 31.940826416015625]

In [105]:
XT = pd.read_csv("Test/Test_Data.csv")
empty2 = np.where(pd.isnull(XT))
print(empty2[0].shape)
coloumns_name2 = XT.columns
print(coloumns_name2[0])

(1700,)
Id


In [106]:
for i in range(empty2[0].shape[0]):
    for j in range(empty2[1].shape[0]):
        row_no = empty2[0][i]
        col_no = empty2[1][j]
        col = coloumns_name2[col_no]
        XT.at[row_no,col] = -1
        


In [108]:
empty2 = np.where(pd.isnull(XT))
print(empty2)

(array([], dtype=int64), array([], dtype=int64))


In [109]:
for col_name in XT.columns:
    le= preprocessing.LabelEncoder()
    print(col_name)
    XT[col_name] = le.fit_transform(XT[col_name])
    print(1)

Id
1
MSSubClass
1
MSZoning
1
LotFrontage
1
LotArea
1
Street
1
Alley
1
LotShape
1
LandContour
1
Utilities
1
LotConfig
1
LandSlope
1
Neighborhood
1
Condition1
1
Condition2
1
BldgType
1
HouseStyle
1
OverallQual
1
OverallCond
1
YearBuilt
1
YearRemodAdd
1
RoofStyle
1
RoofMatl
1
Exterior1st
1
Exterior2nd
1
MasVnrType
1
MasVnrArea
1
ExterQual
1
ExterCond
1
Foundation
1
BsmtQual
1
BsmtCond
1
BsmtExposure
1
BsmtFinType1
1
BsmtFinSF1
1
BsmtFinType2
1
BsmtFinSF2
1
BsmtUnfSF
1
TotalBsmtSF
1
Heating
1
HeatingQC
1
CentralAir
1
Electrical
1
1stFlrSF
1
2ndFlrSF
1
LowQualFinSF
1
GrLivArea
1
BsmtFullBath
1
BsmtHalfBath
1
FullBath
1
HalfBath
1
BedroomAbvGr
1
KitchenAbvGr
1
KitchenQual
1
TotRmsAbvGrd
1
Functional
1
Fireplaces
1
FireplaceQu
1
GarageType
1
GarageYrBlt
1
GarageFinish
1
GarageCars
1
GarageArea
1
GarageQual
1
GarageCond
1
PavedDrive
1
WoodDeckSF
1
OpenPorchSF
1
EnclosedPorch
1
3SsnPorch
1
ScreenPorch
1
PoolArea
1
PoolQC
1
Fence
1
MiscFeature
1
MiscVal
1
MoSold
1
YrSold
1
SaleType
1
SaleConditi

In [114]:

XT_new  = XT.values
XT_new = XT_new[:,1:]
print(XT_new)

[[1 3 0 ... 3 6 3]
 [0 3 0 ... 1 6 3]
 [0 3 0 ... 1 6 2]
 ...
 [5 3 0 ... 4 6 3]
 [0 3 0 ... 4 6 3]
 [0 3 0 ... 2 6 3]]


In [115]:
out = model.predict(XT_new)

In [116]:
out

array([[  1.694823 ],
       [ 74.2723   ],
       [113.350655 ],
       [ 65.52603  ],
       [ 57.929283 ],
       [289.39993  ],
       [212.35649  ],
       [237.67921  ],
       [176.81493  ],
       [314.78897  ],
       [148.71399  ],
       [178.89365  ],
       [ 48.857094 ],
       [110.7964   ],
       [ 98.371574 ],
       [278.09903  ],
       [175.92477  ],
       [137.66513  ],
       [ 83.96662  ],
       [ 52.021492 ],
       [ 35.523285 ],
       [235.41939  ],
       [ 28.741735 ],
       [ 55.13447  ],
       [140.49171  ],
       [ 60.4614   ],
       [231.04771  ],
       [263.33514  ],
       [237.02036  ],
       [122.8685   ],
       [137.902    ],
       [ 98.13118  ],
       [ 78.69235  ],
       [233.90608  ],
       [170.12209  ],
       [ 45.137527 ],
       [ 38.57198  ],
       [ 29.334143 ],
       [220.77367  ],
       [ 48.42811  ],
       [ 79.094444 ],
       [189.79738  ],
       [296.2601   ],
       [ 47.057327 ],
       [ 19.07659  ],
       [ 4

In [117]:
Id = []
for i in range(1101,1461):
    Id.append(i)

In [118]:
Id

[1101,
 1102,
 1103,
 1104,
 1105,
 1106,
 1107,
 1108,
 1109,
 1110,
 1111,
 1112,
 1113,
 1114,
 1115,
 1116,
 1117,
 1118,
 1119,
 1120,
 1121,
 1122,
 1123,
 1124,
 1125,
 1126,
 1127,
 1128,
 1129,
 1130,
 1131,
 1132,
 1133,
 1134,
 1135,
 1136,
 1137,
 1138,
 1139,
 1140,
 1141,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1150,
 1151,
 1152,
 1153,
 1154,
 1155,
 1156,
 1157,
 1158,
 1159,
 1160,
 1161,
 1162,
 1163,
 1164,
 1165,
 1166,
 1167,
 1168,
 1169,
 1170,
 1171,
 1172,
 1173,
 1174,
 1175,
 1176,
 1177,
 1178,
 1179,
 1180,
 1181,
 1182,
 1183,
 1184,
 1185,
 1186,
 1187,
 1188,
 1189,
 1190,
 1191,
 1192,
 1193,
 1194,
 1195,
 1196,
 1197,
 1198,
 1199,
 1200,
 1201,
 1202,
 1203,
 1204,
 1205,
 1206,
 1207,
 1208,
 1209,
 1210,
 1211,
 1212,
 1213,
 1214,
 1215,
 1216,
 1217,
 1218,
 1219,
 1220,
 1221,
 1222,
 1223,
 1224,
 1225,
 1226,
 1227,
 1228,
 1229,
 1230,
 1231,
 1232,
 1233,
 1234,
 1235,
 1236,
 1237,
 1238,
 1239,
 1240,
 1241,
 1242,
 1243,

In [124]:
df = pd.DataFrame(data = Id,columns=["Id"])


In [126]:
df['SalePrice'] = out
print(df.head)

<bound method NDFrame.head of        Id   SalePrice
0    1101    1.694823
1    1102   74.272301
2    1103  113.350655
3    1104   65.526031
4    1105   57.929283
..    ...         ...
355  1456  172.053284
356  1457  208.327896
357  1458  182.269058
358  1459  101.145950
359  1460  118.374359

[360 rows x 2 columns]>


In [127]:
df

Id   SalePrice
0    1101    1.694823
1    1102   74.272301
2    1103  113.350655
3    1104   65.526031
4    1105   57.929283
..    ...         ...
355  1456  172.053284
356  1457  208.327896
357  1458  182.269058
358  1459  101.145950
359  1460  118.374359

[360 rows x 2 columns]

In [128]:
df.to_csv("output.csv",index = False)

In [129]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_25 (Dense)             (None, 20)                1600      
_________________________________________________________________
dense_26 (Dense)             (None, 20)                420       
_________________________________________________________________
dense_27 (Dense)             (None, 1)                 21        
Total params: 2,041
Trainable params: 2,041
Non-trainable params: 0
_________________________________________________________________
